### ISSUE TITLE
Mining Dashboard (Phase 1): Create new page for Bitcoin mining pools hash rate distribution

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#463]
- [ ] Create new blocks database table https://github.com/mempool/mempool/issues/63
- [ ] Move miner identifcation from frontend to backend and the new blocks table and push this new data in the Websocket https://github.com/mempool/mempool/issues/163
- [ ] Create a new backend API for the blocks data, to be fetched when viewing a old block to display miner, fee span and median fee. https://github.com/mempool/mempool/issues/462
- [ ] Use the new database table for the data for latest blocks (dashboard and blocks page) https://github.com/mempool/mempool/issues/464 Also fixes #464 

![photo5181932481790716341](https://user-images.githubusercontent.com/232186/115271144-00699900-a178-11eb-89b4-3030a678921d.jpeg)

<img width="1214" alt="Screen Shot 2021-10-18 at 13 43 52" src="https://user-images.githubusercontent.com/8561090/137707719-a04b75cb-8031-4c1b-a518-eca5dad66641.png">

**Comment by wiz** [comment]
Don't forget APIs to go with all this data

**Comment by softsimon** [comment]
Broke this up into more specific and describing tasks:
#1047
#1048
#1049
#1050
